# Tercer ejemplo
version: "3"
services:
  web:
    build: .
    image: miappweb
    ports:
      - "5000:80"
    networks:
      - red-mi-app-web

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"
    networks:
      - red-mi-app-web

volumes:
  redisdata:

networks:
  red-mi-app-web:
