# Primer ejemplo de docker-compose.yml
version: "3"
services:
  web:
    image: ostua/repopython:0.02
    deploy:
      replicas: 8
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
