# Primer ejemplo de docker-compose.yml
version: "3"
services:
  web:
    image: ostua/miprimerrepo:1.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "7080:80"
    networks:
      - webnet
networks:
  webnet:
